#!/bin/sh

#-----------------------------------------------------------------------------
# Copyright (c) 2011-2013, The BIOM Format Development Team.
#
# Distributed under the terms of the Modified BSD License.
#
# The full license is in the file COPYING.txt, distributed with this software.
#-----------------------------------------------------------------------------

# __author__ = "Greg Caporaso"
# __copyright__ = "Copyright 2011-2013, The BIOM Format Development Team"
# __credits__ = ["Daniel McDonald",
#                "Greg Caporaso",
#                "Jai Ram Rideout"]
# __license__ = "BSD"
# __url__ = "http://biom-format.org"
# __version__ = "2.1.4"
# __maintainer__ = "Greg Caporaso"
# __email__ = "gregcaporaso@gmail.com"

exec pyqi --driver-name biom --command-config-module biom.interfaces.optparse.config -- "$@"
