#!/bin/sh

# __author__ = "Greg Caporaso"
# __copyright__ = "Copyright 2013, The BIOM-Format project"
# __credits__ = ["Daniel McDonald", 
#                "Greg Caporaso", 
#                "Jai Ram Rideout"]
# __license__ = "GPL"
# __url__ = "http://biom-format.org"
# __version__ = "1.2.0"
# __maintainer__ = "Greg Caporaso"
# __email__ = "gregcaporaso@gmail.com"

exec pyqi --driver-name biom --command-config-module biom.interfaces.optparse.config -- "$@"
